[2024-09-09T06:35:50.428+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-09T06:35:50.469+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: trino_query_dag.insert_data_inc scheduled__2024-09-08T00:00:00+00:00 [queued]>
[2024-09-09T06:35:50.480+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: trino_query_dag.insert_data_inc scheduled__2024-09-08T00:00:00+00:00 [queued]>
[2024-09-09T06:35:50.481+0000] {taskinstance.py:2306} INFO - Starting attempt 11 of 11
[2024-09-09T06:35:50.510+0000] {taskinstance.py:2330} INFO - Executing <Task(TrinoOperator): insert_data_inc> on 2024-09-08 00:00:00+00:00
[2024-09-09T06:35:50.518+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=68679) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-09T06:35:50.520+0000] {standard_task_runner.py:64} INFO - Started process 68694 to run task
[2024-09-09T06:35:50.518+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'trino_query_dag', 'insert_data_inc', 'scheduled__2024-09-08T00:00:00+00:00', '--job-id', '44', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpjydrmcia']
[2024-09-09T06:35:50.521+0000] {standard_task_runner.py:91} INFO - Job 44: Subtask insert_data_inc
[2024-09-09T06:35:50.540+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-09-09T06:35:50.610+0000] {task_command.py:426} INFO - Running <TaskInstance: trino_query_dag.insert_data_inc scheduled__2024-09-08T00:00:00+00:00 [running]> on host 92783cd12528
[2024-09-09T06:35:50.622+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:356 DeprecationWarning: The sql_engine_encoding option in [core] has been moved to the sql_engine_encoding option in [database] - the old setting has been used, but please update your config.
[2024-09-09T06:35:50.719+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/utils/log/secrets_masker.py:84 DeprecationWarning: The sensitive_variable_fields option in [admin] has been moved to the sensitive_var_conn_names option in [core] - the old setting has been used, but please update your config.
[2024-09-09T06:35:50.752+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='trino_query_dag' AIRFLOW_CTX_TASK_ID='insert_data_inc' AIRFLOW_CTX_EXECUTION_DATE='2024-09-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='11' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-08T00:00:00+00:00'
[2024-09-09T06:35:50.754+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-09T06:35:50.778+0000] {sql.py:282} INFO - Executing: insert into hive.test.nganhangso select * from sqlserver.dbo.nganhangso where date_format(d_date_time, '%Y%m%d') = '20240627'
[2024-09-09T06:35:50.800+0000] {base.py:84} INFO - Using connection ID 'my_trino_connection' for task execution.
[2024-09-09T06:35:50.822+0000] {base.py:84} INFO - Using connection ID 'my_trino_connection' for task execution.
[2024-09-09T06:35:50.832+0000] {base.py:84} INFO - Using connection ID 'my_trino_connection' for task execution.
[2024-09-09T06:35:50.839+0000] {sql.py:495} INFO - Running statement: insert into hive.test.nganhangso select * from sqlserver.dbo.nganhangso where date_format(d_date_time, '%Y%m%d') = '20240627', parameters: None
[2024-09-09T06:35:51.973+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-09T06:35:51.974+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 288, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 442, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 500, in _run_command
    cur.execute(sql_statement)
  File "/home/airflow/.local/lib/python3.12/site-packages/trino/dbapi.py", line 589, in execute
    self._iterator = iter(self._query.execute())
                          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/trino/client.py", line 819, in execute
    self._result.rows += self.fetch()
                         ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/trino/client.py", line 839, in fetch
    status = self._request.process(response)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/trino/client.py", line 611, in process
    raise self._process_error(response["error"], response.get("id"))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/trino/client.py", line 581, in _process_error
    raise exceptions.TrinoExternalError(error, query_id)
trino.exceptions.TrinoExternalError: TrinoExternalError(type=EXTERNAL, name=HIVE_WRITER_CLOSE_ERROR, message="Error committing write parquet to Hive", query_id=20240909_052051_00078_9aasa)
[2024-09-09T06:35:52.008+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=trino_query_dag, task_id=insert_data_inc, run_id=scheduled__2024-09-08T00:00:00+00:00, execution_date=20240908T000000, start_date=20240909T063550, end_date=20240909T063552
[2024-09-09T06:35:52.037+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 44 for task insert_data_inc (TrinoExternalError(type=EXTERNAL, name=HIVE_WRITER_CLOSE_ERROR, message="Error committing write parquet to Hive", query_id=20240909_052051_00078_9aasa); 68694)
[2024-09-09T06:35:52.081+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-09-09T06:35:52.124+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py:1297 AirflowProviderDeprecationWarning: Call to deprecated class TrinoOperator. (Please use `airflow.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.)
[2024-09-09T06:35:52.176+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-09T06:35:52.184+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
