[2024-09-26T00:37:39.102+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-26T00:37:39.214+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: query_dag_iron.insert_data_inc scheduled__2024-09-25T00:00:00+00:00 [queued]>
[2024-09-26T00:37:39.232+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: query_dag_iron.insert_data_inc scheduled__2024-09-25T00:00:00+00:00 [queued]>
[2024-09-26T00:37:39.290+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-09-26T00:37:40.080+0000] {taskinstance.py:2330} INFO - Executing <Task(TrinoOperator): insert_data_inc> on 2024-09-25 00:00:00+00:00
[2024-09-26T00:37:40.901+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=83758) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-26T00:37:40.910+0000] {standard_task_runner.py:64} INFO - Started process 83799 to run task
[2024-09-26T00:37:40.915+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'query_dag_iron', 'insert_data_inc', 'scheduled__2024-09-25T00:00:00+00:00', '--job-id', '552', '--raw', '--subdir', 'DAGS_FOLDER/iron.py', '--cfg-path', '/tmp/tmpv4xpuhof']
[2024-09-26T00:37:40.952+0000] {standard_task_runner.py:91} INFO - Job 552: Subtask insert_data_inc
[2024-09-26T00:37:44.333+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-09-26T00:37:44.506+0000] {task_command.py:426} INFO - Running <TaskInstance: query_dag_iron.insert_data_inc scheduled__2024-09-25T00:00:00+00:00 [running]> on host 92783cd12528
[2024-09-26T00:37:44.513+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:356 DeprecationWarning: The sql_engine_encoding option in [core] has been moved to the sql_engine_encoding option in [database] - the old setting has been used, but please update your config.
[2024-09-26T00:37:45.668+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/utils/log/secrets_masker.py:84 DeprecationWarning: The sensitive_variable_fields option in [admin] has been moved to the sensitive_var_conn_names option in [core] - the old setting has been used, but please update your config.
[2024-09-26T00:37:46.939+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='query_dag_iron' AIRFLOW_CTX_TASK_ID='insert_data_inc' AIRFLOW_CTX_EXECUTION_DATE='2024-09-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-25T00:00:00+00:00'
[2024-09-26T00:37:46.959+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-26T00:37:47.061+0000] {sql.py:282} INFO - Executing: insert into hive.iron.customer select *  from sqlserver.dbo.soul
[2024-09-26T00:37:47.097+0000] {base.py:84} INFO - Using connection ID 'my_trino_connection' for task execution.
[2024-09-26T00:37:47.131+0000] {base.py:84} INFO - Using connection ID 'my_trino_connection' for task execution.
[2024-09-26T00:37:47.147+0000] {base.py:84} INFO - Using connection ID 'my_trino_connection' for task execution.
[2024-09-26T00:37:47.196+0000] {sql.py:495} INFO - Running statement: insert into hive.iron.customer select *  from sqlserver.dbo.soul, parameters: None
[2024-09-26T00:37:51.775+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-26T00:37:51.781+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 288, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 442, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 500, in _run_command
    cur.execute(sql_statement)
  File "/home/airflow/.local/lib/python3.12/site-packages/trino/dbapi.py", line 589, in execute
    self._iterator = iter(self._query.execute())
                          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/trino/client.py", line 819, in execute
    self._result.rows += self.fetch()
                         ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/trino/client.py", line 839, in fetch
    status = self._request.process(response)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/trino/client.py", line 611, in process
    raise self._process_error(response["error"], response.get("id"))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/trino/client.py", line 581, in _process_error
    raise exceptions.TrinoExternalError(error, query_id)
trino.exceptions.TrinoExternalError: TrinoExternalError(type=EXTERNAL, name=JDBC_ERROR, message="SQL Server did not return a response. The connection has been closed.", query_id=20240924_184528_00092_bui7k)
[2024-09-26T00:37:51.859+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=query_dag_iron, task_id=insert_data_inc, run_id=scheduled__2024-09-25T00:00:00+00:00, execution_date=20240925T000000, start_date=20240926T003739, end_date=20240926T003751
[2024-09-26T00:37:56.296+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 552 for task insert_data_inc (TrinoExternalError(type=EXTERNAL, name=JDBC_ERROR, message="SQL Server did not return a response. The connection has been closed.", query_id=20240924_184528_00092_bui7k); 83799)
[2024-09-26T00:37:56.408+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-09-26T00:37:56.437+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py:1297 AirflowProviderDeprecationWarning: Call to deprecated class TrinoOperator. (Please use `airflow.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.)
[2024-09-26T00:37:56.472+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-26T00:37:57.949+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
