[2024-08-27T01:00:02.841+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-27T01:00:02.878+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: trino_query_dag_ivory.insert_data_inc scheduled__2024-08-27T00:00:00+00:00 [queued]>
[2024-08-27T01:00:02.888+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: trino_query_dag_ivory.insert_data_inc scheduled__2024-08-27T00:00:00+00:00 [queued]>
[2024-08-27T01:00:02.890+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-08-27T01:00:02.908+0000] {taskinstance.py:2330} INFO - Executing <Task(TrinoOperator): insert_data_inc> on 2024-08-27 00:00:00+00:00
[2024-08-27T01:00:02.914+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=18003) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-08-27T01:00:02.915+0000] {standard_task_runner.py:64} INFO - Started process 18005 to run task
[2024-08-27T01:00:02.914+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'trino_query_dag_ivory', 'insert_data_inc', 'scheduled__2024-08-27T00:00:00+00:00', '--job-id', '343', '--raw', '--subdir', 'DAGS_FOLDER/ivory.py', '--cfg-path', '/tmp/tmpix0n3v38']
[2024-08-27T01:00:02.917+0000] {standard_task_runner.py:91} INFO - Job 343: Subtask insert_data_inc
[2024-08-27T01:00:02.938+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-08-27T01:00:02.984+0000] {task_command.py:426} INFO - Running <TaskInstance: trino_query_dag_ivory.insert_data_inc scheduled__2024-08-27T00:00:00+00:00 [running]> on host b476143e3d64
[2024-08-27T01:00:03.086+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='trino_query_dag_ivory' AIRFLOW_CTX_TASK_ID='insert_data_inc' AIRFLOW_CTX_EXECUTION_DATE='2024-08-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-27T00:00:00+00:00'
[2024-08-27T01:00:03.087+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-27T01:00:03.102+0000] {sql.py:282} INFO - Executing: insert into hive.ivory.customer select *  from sqlserver.dbo.customer
[2024-08-27T01:00:03.120+0000] {base.py:84} INFO - Using connection ID 'my_trino_connection' for task execution.
[2024-08-27T01:00:03.129+0000] {base.py:84} INFO - Using connection ID 'my_trino_connection' for task execution.
[2024-08-27T01:00:03.138+0000] {base.py:84} INFO - Using connection ID 'my_trino_connection' for task execution.
[2024-08-27T01:00:03.142+0000] {sql.py:495} INFO - Running statement: insert into hive.ivory.customer select *  from sqlserver.dbo.customer, parameters: None
[2024-08-27T01:00:03.461+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-27T01:00:03.463+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 288, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 442, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 500, in _run_command
    cur.execute(sql_statement)
  File "/home/airflow/.local/lib/python3.12/site-packages/trino/dbapi.py", line 589, in execute
    self._iterator = iter(self._query.execute())
                          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/trino/client.py", line 819, in execute
    self._result.rows += self.fetch()
                         ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/trino/client.py", line 839, in fetch
    status = self._request.process(response)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/trino/client.py", line 611, in process
    raise self._process_error(response["error"], response.get("id"))
trino.exceptions.TrinoUserError: TrinoUserError(type=USER_ERROR, name=TYPE_MISMATCH, message="Insert query has mismatched column types: Table: [integer, date, varchar(50), varchar(100), varchar(50), varchar(10), varchar(50), varchar(20), varchar(50)], Query: [double, timestamp(3), varchar(255), varchar(255), varchar(255), double, varchar(255), double, varchar(255)]", query_id=20240826_103716_00097_kfczv)
[2024-08-27T01:00:03.477+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=trino_query_dag_ivory, task_id=insert_data_inc, run_id=scheduled__2024-08-27T00:00:00+00:00, execution_date=20240827T000000, start_date=20240827T010002, end_date=20240827T010003
[2024-08-27T01:00:03.491+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 343 for task insert_data_inc (TrinoUserError(type=USER_ERROR, name=TYPE_MISMATCH, message="Insert query has mismatched column types: Table: [integer, date, varchar(50), varchar(100), varchar(50), varchar(10), varchar(50), varchar(20), varchar(50)], Query: [double, timestamp(3), varchar(255), varchar(255), varchar(255), double, varchar(255), double, varchar(255)]", query_id=20240826_103716_00097_kfczv); 18005)
[2024-08-27T01:00:03.534+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-08-27T01:00:03.548+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py:1297 AirflowProviderDeprecationWarning: Call to deprecated class TrinoOperator. (Please use `airflow.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.)
[2024-08-27T01:00:03.563+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-27T01:00:03.566+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-08-27T01:56:50.594+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-27T01:56:50.632+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: trino_query_dag_ivory.insert_data_inc scheduled__2024-08-27T00:00:00+00:00 [queued]>
[2024-08-27T01:56:50.648+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: trino_query_dag_ivory.insert_data_inc scheduled__2024-08-27T00:00:00+00:00 [queued]>
[2024-08-27T01:56:50.648+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-08-27T01:56:50.663+0000] {taskinstance.py:2330} INFO - Executing <Task(TrinoOperator): insert_data_inc> on 2024-08-27 00:00:00+00:00
[2024-08-27T01:56:50.669+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=19253) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-08-27T01:56:50.670+0000] {standard_task_runner.py:64} INFO - Started process 19255 to run task
[2024-08-27T01:56:50.670+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'trino_query_dag_ivory', 'insert_data_inc', 'scheduled__2024-08-27T00:00:00+00:00', '--job-id', '383', '--raw', '--subdir', 'DAGS_FOLDER/ivory.py', '--cfg-path', '/tmp/tmpkujub6yw']
[2024-08-27T01:56:50.672+0000] {standard_task_runner.py:91} INFO - Job 383: Subtask insert_data_inc
[2024-08-27T01:56:50.688+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-08-27T01:56:50.760+0000] {task_command.py:426} INFO - Running <TaskInstance: trino_query_dag_ivory.insert_data_inc scheduled__2024-08-27T00:00:00+00:00 [running]> on host b476143e3d64
[2024-08-27T01:56:50.856+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='trino_query_dag_ivory' AIRFLOW_CTX_TASK_ID='insert_data_inc' AIRFLOW_CTX_EXECUTION_DATE='2024-08-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-27T00:00:00+00:00'
[2024-08-27T01:56:50.857+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-27T01:56:50.871+0000] {sql.py:282} INFO - Executing: insert into hive.ivory.customer select *  from sqlserver.dbo.customer
[2024-08-27T01:56:50.889+0000] {base.py:84} INFO - Using connection ID 'my_trino_connection' for task execution.
[2024-08-27T01:56:50.898+0000] {base.py:84} INFO - Using connection ID 'my_trino_connection' for task execution.
[2024-08-27T01:56:50.905+0000] {base.py:84} INFO - Using connection ID 'my_trino_connection' for task execution.
[2024-08-27T01:56:50.909+0000] {sql.py:495} INFO - Running statement: insert into hive.ivory.customer select *  from sqlserver.dbo.customer, parameters: None
[2024-08-27T01:56:50.998+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-27T01:56:50.999+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 288, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 442, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 500, in _run_command
    cur.execute(sql_statement)
  File "/home/airflow/.local/lib/python3.12/site-packages/trino/dbapi.py", line 589, in execute
    self._iterator = iter(self._query.execute())
                          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/trino/client.py", line 819, in execute
    self._result.rows += self.fetch()
                         ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/trino/client.py", line 839, in fetch
    status = self._request.process(response)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/trino/client.py", line 611, in process
    raise self._process_error(response["error"], response.get("id"))
trino.exceptions.TrinoUserError: TrinoUserError(type=USER_ERROR, name=TYPE_MISMATCH, message="Insert query has mismatched column types: Table: [integer, date, varchar(50), varchar(100), varchar(50), varchar(10), varchar(50), varchar(20), varchar(50)], Query: [double, timestamp(3), varchar(255), varchar(255), varchar(255), double, varchar(255), double, varchar(255)]", query_id=20240826_111651_00128_kfczv)
[2024-08-27T01:56:51.010+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=trino_query_dag_ivory, task_id=insert_data_inc, run_id=scheduled__2024-08-27T00:00:00+00:00, execution_date=20240827T000000, start_date=20240827T015650, end_date=20240827T015651
[2024-08-27T01:56:51.023+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 383 for task insert_data_inc (TrinoUserError(type=USER_ERROR, name=TYPE_MISMATCH, message="Insert query has mismatched column types: Table: [integer, date, varchar(50), varchar(100), varchar(50), varchar(10), varchar(50), varchar(20), varchar(50)], Query: [double, timestamp(3), varchar(255), varchar(255), varchar(255), double, varchar(255), double, varchar(255)]", query_id=20240826_111651_00128_kfczv); 19255)
[2024-08-27T01:56:51.047+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-08-27T01:56:51.060+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py:1297 AirflowProviderDeprecationWarning: Call to deprecated class TrinoOperator. (Please use `airflow.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.)
[2024-08-27T01:56:51.080+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-27T01:56:51.083+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-08-28T00:50:27.740+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-28T00:50:27.993+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: trino_query_dag_ivory.insert_data_inc scheduled__2024-08-27T00:00:00+00:00 [queued]>
[2024-08-28T00:50:28.004+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: trino_query_dag_ivory.insert_data_inc scheduled__2024-08-27T00:00:00+00:00 [queued]>
[2024-08-28T00:50:28.004+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-08-28T00:50:28.498+0000] {taskinstance.py:2330} INFO - Executing <Task(TrinoOperator): insert_data_inc> on 2024-08-27 00:00:00+00:00
[2024-08-28T00:50:28.563+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=21765) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-08-28T00:50:28.581+0000] {standard_task_runner.py:64} INFO - Started process 21782 to run task
[2024-08-28T00:50:28.573+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'trino_query_dag_ivory', 'insert_data_inc', 'scheduled__2024-08-27T00:00:00+00:00', '--job-id', '545', '--raw', '--subdir', 'DAGS_FOLDER/ivory.py', '--cfg-path', '/tmp/tmp4iicl99y']
[2024-08-28T00:50:28.599+0000] {standard_task_runner.py:91} INFO - Job 545: Subtask insert_data_inc
[2024-08-28T00:50:30.760+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-08-28T00:50:30.861+0000] {task_command.py:426} INFO - Running <TaskInstance: trino_query_dag_ivory.insert_data_inc scheduled__2024-08-27T00:00:00+00:00 [running]> on host b476143e3d64
[2024-08-28T00:50:41.062+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='trino_query_dag_ivory' AIRFLOW_CTX_TASK_ID='insert_data_inc' AIRFLOW_CTX_EXECUTION_DATE='2024-08-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-27T00:00:00+00:00'
[2024-08-28T00:50:41.078+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-28T00:50:41.217+0000] {sql.py:282} INFO - Executing: insert into hive.ivory.customer select *  from sqlserver.dbo.customer
[2024-08-28T00:50:41.282+0000] {base.py:84} INFO - Using connection ID 'my_trino_connection' for task execution.
[2024-08-28T00:50:41.297+0000] {base.py:84} INFO - Using connection ID 'my_trino_connection' for task execution.
[2024-08-28T00:50:41.308+0000] {base.py:84} INFO - Using connection ID 'my_trino_connection' for task execution.
[2024-08-28T00:50:41.314+0000] {sql.py:495} INFO - Running statement: insert into hive.ivory.customer select *  from sqlserver.dbo.customer, parameters: None
[2024-08-28T00:51:28.059+0000] {sql.py:504} INFO - Rows affected: 13
[2024-08-28T00:51:39.735+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-28T00:51:57.500+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=trino_query_dag_ivory, task_id=insert_data_inc, run_id=scheduled__2024-08-27T00:00:00+00:00, execution_date=20240827T000000, start_date=20240828T005027, end_date=20240828T005157
[2024-08-28T00:51:59.887+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-08-28T00:51:59.899+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py:1297 AirflowProviderDeprecationWarning: Call to deprecated class TrinoOperator. (Please use `airflow.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.)
[2024-08-28T00:51:59.913+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-08-28T00:52:05.685+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
