[2024-08-26T00:44:07.886+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-26T00:44:08.116+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: trino_query_dag.insert_data_inc scheduled__2024-08-25T00:00:00+00:00 [queued]>
[2024-08-26T00:44:08.186+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: trino_query_dag.insert_data_inc scheduled__2024-08-25T00:00:00+00:00 [queued]>
[2024-08-26T00:44:08.191+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-08-26T00:44:08.252+0000] {taskinstance.py:2330} INFO - Executing <Task(TrinoOperator): insert_data_inc> on 2024-08-25 00:00:00+00:00
[2024-08-26T00:44:08.270+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=182) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-08-26T00:44:08.281+0000] {standard_task_runner.py:64} INFO - Started process 199 to run task
[2024-08-26T00:44:08.277+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'trino_query_dag', 'insert_data_inc', 'scheduled__2024-08-25T00:00:00+00:00', '--job-id', '206', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmprzamaj7g']
[2024-08-26T00:44:08.285+0000] {standard_task_runner.py:91} INFO - Job 206: Subtask insert_data_inc
[2024-08-26T00:44:08.532+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-08-26T00:44:08.779+0000] {task_command.py:426} INFO - Running <TaskInstance: trino_query_dag.insert_data_inc scheduled__2024-08-25T00:00:00+00:00 [running]> on host b476143e3d64
[2024-08-26T00:44:09.450+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='trino_query_dag' AIRFLOW_CTX_TASK_ID='insert_data_inc' AIRFLOW_CTX_EXECUTION_DATE='2024-08-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-25T00:00:00+00:00'
[2024-08-26T00:44:09.465+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-26T00:44:09.520+0000] {sql.py:282} INFO - Executing: insert into hive.test.nganhangso select * from sqlserver.dbo.nganhangso where date_format(d_date_time, '%Y%m%d') = '20240627'
[2024-08-26T00:44:09.622+0000] {base.py:84} INFO - Using connection ID 'my_trino_connection' for task execution.
[2024-08-26T00:44:09.653+0000] {base.py:84} INFO - Using connection ID 'my_trino_connection' for task execution.
[2024-08-26T00:44:09.688+0000] {base.py:84} INFO - Using connection ID 'my_trino_connection' for task execution.
[2024-08-26T00:44:09.700+0000] {sql.py:495} INFO - Running statement: insert into hive.test.nganhangso select * from sqlserver.dbo.nganhangso where date_format(d_date_time, '%Y%m%d') = '20240627', parameters: None
[2024-08-26T00:44:09.995+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-26T00:44:09.996+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 288, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 442, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 500, in _run_command
    cur.execute(sql_statement)
  File "/home/airflow/.local/lib/python3.12/site-packages/trino/dbapi.py", line 589, in execute
    self._iterator = iter(self._query.execute())
                          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/trino/client.py", line 819, in execute
    self._result.rows += self.fetch()
                         ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/trino/client.py", line 839, in fetch
    status = self._request.process(response)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/trino/client.py", line 611, in process
    raise self._process_error(response["error"], response.get("id"))
trino.exceptions.TrinoQueryError: TrinoQueryError(type=INTERNAL_ERROR, name=SERVER_STARTING_UP, message="Trino server is still initializing", query_id=20240826_004409_00002_kfczv)
[2024-08-26T00:44:10.081+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=trino_query_dag, task_id=insert_data_inc, run_id=scheduled__2024-08-25T00:00:00+00:00, execution_date=20240825T000000, start_date=20240826T004408, end_date=20240826T004410
[2024-08-26T00:44:10.144+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 206 for task insert_data_inc (TrinoQueryError(type=INTERNAL_ERROR, name=SERVER_STARTING_UP, message="Trino server is still initializing", query_id=20240826_004409_00002_kfczv); 199)
[2024-08-26T00:44:10.277+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-08-26T00:44:10.528+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
