[2024-10-11T08:15:19.920+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-11T08:15:20.087+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: query_dag_irenen.insert_data_inc scheduled__2024-10-10T00:00:00+00:00 [queued]>
[2024-10-11T08:15:20.105+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: query_dag_irenen.insert_data_inc scheduled__2024-10-10T00:00:00+00:00 [queued]>
[2024-10-11T08:15:20.150+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-10-11T08:15:20.438+0000] {taskinstance.py:2330} INFO - Executing <Task(TrinoOperator): insert_data_inc> on 2024-10-10 00:00:00+00:00
[2024-10-11T08:15:20.445+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=328) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-10-11T08:15:20.447+0000] {standard_task_runner.py:64} INFO - Started process 361 to run task
[2024-10-11T08:15:20.461+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'query_dag_irenen', 'insert_data_inc', 'scheduled__2024-10-10T00:00:00+00:00', '--job-id', '991', '--raw', '--subdir', 'DAGS_FOLDER/irenen.py', '--cfg-path', '/tmp/tmpgxb0r9oc']
[2024-10-11T08:15:20.465+0000] {standard_task_runner.py:91} INFO - Job 991: Subtask insert_data_inc
[2024-10-11T08:15:20.782+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-10-11T08:15:20.868+0000] {task_command.py:426} INFO - Running <TaskInstance: query_dag_irenen.insert_data_inc scheduled__2024-10-10T00:00:00+00:00 [running]> on host 92783cd12528
[2024-10-11T08:15:20.873+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:356 DeprecationWarning: The sql_engine_encoding option in [core] has been moved to the sql_engine_encoding option in [database] - the old setting has been used, but please update your config.
[2024-10-11T08:15:21.255+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/utils/log/secrets_masker.py:84 DeprecationWarning: The sensitive_variable_fields option in [admin] has been moved to the sensitive_var_conn_names option in [core] - the old setting has been used, but please update your config.
[2024-10-11T08:15:21.562+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='query_dag_irenen' AIRFLOW_CTX_TASK_ID='insert_data_inc' AIRFLOW_CTX_EXECUTION_DATE='2024-10-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-10T00:00:00+00:00'
[2024-10-11T08:15:21.592+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-11T08:15:21.614+0000] {sql.py:282} INFO - Executing: insert into hive.irenen.sou         WITH sou_cte AS (         SELECT * FROM sqlserver.dbo.Sou         where hour =22        ) SELECT * FROM sou_cte
[2024-10-11T08:15:21.660+0000] {base.py:84} INFO - Using connection ID 'my_trino_connection' for task execution.
[2024-10-11T08:15:21.696+0000] {base.py:84} INFO - Using connection ID 'my_trino_connection' for task execution.
[2024-10-11T08:15:21.730+0000] {base.py:84} INFO - Using connection ID 'my_trino_connection' for task execution.
[2024-10-11T08:15:21.896+0000] {sql.py:495} INFO - Running statement: insert into hive.irenen.sou         WITH sou_cte AS (         SELECT * FROM sqlserver.dbo.Sou         where hour =22        ) SELECT * FROM sou_cte, parameters: None
[2024-10-11T08:15:22.375+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-11T08:15:22.377+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 288, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 442, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 500, in _run_command
    cur.execute(sql_statement)
  File "/home/airflow/.local/lib/python3.12/site-packages/trino/dbapi.py", line 589, in execute
    self._iterator = iter(self._query.execute())
                          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/trino/client.py", line 819, in execute
    self._result.rows += self.fetch()
                         ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/trino/client.py", line 839, in fetch
    status = self._request.process(response)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/trino/client.py", line 611, in process
    raise self._process_error(response["error"], response.get("id"))
trino.exceptions.TrinoQueryError: TrinoQueryError(type=INTERNAL_ERROR, name=SERVER_STARTING_UP, message="Trino server is still initializing", query_id=20241011_081521_00000_wpsnq)
[2024-10-11T08:15:22.433+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=query_dag_irenen, task_id=insert_data_inc, run_id=scheduled__2024-10-10T00:00:00+00:00, execution_date=20241010T000000, start_date=20241011T081520, end_date=20241011T081522
[2024-10-11T08:15:22.468+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 991 for task insert_data_inc (TrinoQueryError(type=INTERNAL_ERROR, name=SERVER_STARTING_UP, message="Trino server is still initializing", query_id=20241011_081521_00000_wpsnq); 361)
[2024-10-11T08:15:22.516+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-10-11T08:15:22.544+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
