[2024-08-26T00:26:48.027+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-26T00:26:48.200+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: trino_query_dag_ivory.insert_data_inc scheduled__2024-08-25T00:00:00+00:00 [queued]>
[2024-08-26T00:26:48.247+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: trino_query_dag_ivory.insert_data_inc scheduled__2024-08-25T00:00:00+00:00 [queued]>
[2024-08-26T00:26:48.295+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-08-26T00:26:48.471+0000] {taskinstance.py:2330} INFO - Executing <Task(TrinoOperator): insert_data_inc> on 2024-08-25 00:00:00+00:00
[2024-08-26T00:26:48.565+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=2607) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-08-26T00:26:48.581+0000] {standard_task_runner.py:64} INFO - Started process 2612 to run task
[2024-08-26T00:26:48.559+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'trino_query_dag_ivory', 'insert_data_inc', 'scheduled__2024-08-25T00:00:00+00:00', '--job-id', '175', '--raw', '--subdir', 'DAGS_FOLDER/ivory.py', '--cfg-path', '/tmp/tmprgyn77sn']
[2024-08-26T00:26:48.615+0000] {standard_task_runner.py:91} INFO - Job 175: Subtask insert_data_inc
[2024-08-26T00:26:48.794+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-08-26T00:26:49.096+0000] {task_command.py:426} INFO - Running <TaskInstance: trino_query_dag_ivory.insert_data_inc scheduled__2024-08-25T00:00:00+00:00 [running]> on host b476143e3d64
[2024-08-26T00:26:50.155+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='trino_query_dag_ivory' AIRFLOW_CTX_TASK_ID='insert_data_inc' AIRFLOW_CTX_EXECUTION_DATE='2024-08-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-25T00:00:00+00:00'
[2024-08-26T00:26:50.213+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-26T00:26:50.284+0000] {sql.py:282} INFO - Executing: insert into hive.ivory.customer select *  from sqlserver.dbo.customer
[2024-08-26T00:26:50.444+0000] {base.py:84} INFO - Using connection ID 'my_trino_connection' for task execution.
[2024-08-26T00:26:50.494+0000] {base.py:84} INFO - Using connection ID 'my_trino_connection' for task execution.
[2024-08-26T00:26:50.579+0000] {base.py:84} INFO - Using connection ID 'my_trino_connection' for task execution.
[2024-08-26T00:26:50.643+0000] {sql.py:495} INFO - Running statement: insert into hive.ivory.customer select *  from sqlserver.dbo.customer, parameters: None
[2024-08-26T00:27:35.307+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-26T00:27:35.308+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 288, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 442, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 500, in _run_command
    cur.execute(sql_statement)
  File "/home/airflow/.local/lib/python3.12/site-packages/trino/dbapi.py", line 589, in execute
    self._iterator = iter(self._query.execute())
                          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/trino/client.py", line 819, in execute
    self._result.rows += self.fetch()
                         ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/trino/client.py", line 839, in fetch
    status = self._request.process(response)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/trino/client.py", line 611, in process
    raise self._process_error(response["error"], response.get("id"))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/trino/client.py", line 581, in _process_error
    raise exceptions.TrinoExternalError(error, query_id)
trino.exceptions.TrinoExternalError: TrinoExternalError(type=EXTERNAL, name=HIVE_METASTORE_ERROR, message="hive-metastore:9083: java.net.SocketTimeoutException: Read timed out", query_id=20240823_101835_00001_qxrrb)
[2024-08-26T00:27:36.661+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=trino_query_dag_ivory, task_id=insert_data_inc, run_id=scheduled__2024-08-25T00:00:00+00:00, execution_date=20240825T000000, start_date=20240826T002648, end_date=20240826T002736
[2024-08-26T00:27:44.071+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 175 for task insert_data_inc (TrinoExternalError(type=EXTERNAL, name=HIVE_METASTORE_ERROR, message="hive-metastore:9083: java.net.SocketTimeoutException: Read timed out", query_id=20240823_101835_00001_qxrrb); 2612)
[2024-08-26T00:27:44.137+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-08-26T00:27:44.197+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py:1297 AirflowProviderDeprecationWarning: Call to deprecated class TrinoOperator. (Please use `airflow.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.)
[2024-08-26T00:27:44.270+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-26T00:27:50.720+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
