[2024-08-21T08:54:19.113+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-21T08:54:19.170+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: trino_query_dag_irene.insert_data_inc_irene manual__2024-08-21T06:47:17.417444+00:00 [queued]>
[2024-08-21T08:54:19.194+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: trino_query_dag_irene.insert_data_inc_irene manual__2024-08-21T06:47:17.417444+00:00 [queued]>
[2024-08-21T08:54:19.195+0000] {taskinstance.py:2306} INFO - Starting attempt 8 of 8
[2024-08-21T08:54:19.471+0000] {taskinstance.py:2330} INFO - Executing <Task(TrinoOperator): insert_data_inc_irene> on 2024-08-21 06:47:17.417444+00:00
[2024-08-21T08:54:19.490+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=20191) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-08-21T08:54:19.488+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'trino_query_dag_irene', 'insert_data_inc_irene', 'manual__2024-08-21T06:47:17.417444+00:00', '--job-id', '132', '--raw', '--subdir', 'DAGS_FOLDER/irene.py', '--cfg-path', '/tmp/tmpy3ssalwt']
[2024-08-21T08:54:19.493+0000] {standard_task_runner.py:64} INFO - Started process 20192 to run task
[2024-08-21T08:54:19.494+0000] {standard_task_runner.py:91} INFO - Job 132: Subtask insert_data_inc_irene
[2024-08-21T08:54:19.516+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-08-21T08:54:19.564+0000] {task_command.py:426} INFO - Running <TaskInstance: trino_query_dag_irene.insert_data_inc_irene manual__2024-08-21T06:47:17.417444+00:00 [running]> on host b476143e3d64
[2024-08-21T08:54:19.668+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='trino_query_dag_irene' AIRFLOW_CTX_TASK_ID='insert_data_inc_irene' AIRFLOW_CTX_EXECUTION_DATE='2024-08-21T06:47:17.417444+00:00' AIRFLOW_CTX_TRY_NUMBER='8' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-21T06:47:17.417444+00:00'
[2024-08-21T08:54:19.669+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-21T08:54:19.688+0000] {sql.py:282} INFO - Executing: insert into hive.irene.customer select * from sqlserver.dbo.customer WHERE date = CAST('2023-11-25' AS DATE);
[2024-08-21T08:54:19.708+0000] {base.py:84} INFO - Using connection ID 'my_trino_connection' for task execution.
[2024-08-21T08:54:19.719+0000] {base.py:84} INFO - Using connection ID 'my_trino_connection' for task execution.
[2024-08-21T08:54:19.729+0000] {base.py:84} INFO - Using connection ID 'my_trino_connection' for task execution.
[2024-08-21T08:54:19.733+0000] {sql.py:495} INFO - Running statement: insert into hive.irene.customer select * from sqlserver.dbo.customer WHERE date = CAST('2023-11-25' AS DATE);, parameters: None
[2024-08-21T08:54:19.752+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-21T08:54:19.753+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 288, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 442, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 500, in _run_command
    cur.execute(sql_statement)
  File "/home/airflow/.local/lib/python3.12/site-packages/trino/dbapi.py", line 589, in execute
    self._iterator = iter(self._query.execute())
                          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/trino/client.py", line 819, in execute
    self._result.rows += self.fetch()
                         ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/trino/client.py", line 839, in fetch
    status = self._request.process(response)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/trino/client.py", line 611, in process
    raise self._process_error(response["error"], response.get("id"))
trino.exceptions.TrinoUserError: TrinoUserError(type=USER_ERROR, name=SYNTAX_ERROR, message="line 1:109: mismatched input ';'. Expecting: '(', ')', 'ARRAY'", query_id=20240820_071529_00335_mw28g)
[2024-08-21T08:54:19.767+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=trino_query_dag_irene, task_id=insert_data_inc_irene, run_id=manual__2024-08-21T06:47:17.417444+00:00, execution_date=20240821T064717, start_date=20240821T085419, end_date=20240821T085419
[2024-08-21T08:54:19.781+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 132 for task insert_data_inc_irene (TrinoUserError(type=USER_ERROR, name=SYNTAX_ERROR, message="line 1:109: mismatched input ';'. Expecting: '(', ')', 'ARRAY'", query_id=20240820_071529_00335_mw28g); 20192)
[2024-08-21T08:54:19.790+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-08-21T08:54:19.803+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py:1297 AirflowProviderDeprecationWarning: Call to deprecated class TrinoOperator. (Please use `airflow.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.)
[2024-08-21T08:54:19.819+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-21T08:54:19.833+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
